# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envelope.proto',
  package='loggregator.v2',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x65nvelope.proto\x12\x0eloggregator.v2\"\xe6\x02\n\x08\x45nvelope\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x08 \x01(\t\x12\x30\n\x04tags\x18\x03 \x03(\x0b\x32\".loggregator.v2.Envelope.TagsEntry\x12\"\n\x03log\x18\x04 \x01(\x0b\x32\x13.loggregator.v2.LogH\x00\x12*\n\x07\x63ounter\x18\x05 \x01(\x0b\x32\x17.loggregator.v2.CounterH\x00\x12&\n\x05gauge\x18\x06 \x01(\x0b\x32\x15.loggregator.v2.GaugeH\x00\x12&\n\x05timer\x18\x07 \x01(\x0b\x32\x15.loggregator.v2.TimerH\x00\x1a\x42\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.loggregator.v2.Value:\x02\x38\x01\x42\t\n\x07message\"E\n\x05Value\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x11\n\x07integer\x18\x02 \x01(\x03H\x00\x12\x11\n\x07\x64\x65\x63imal\x18\x03 \x01(\x01H\x00\x42\x06\n\x04\x64\x61ta\"X\n\x03Log\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.loggregator.v2.Log.Type\"\x18\n\x04Type\x12\x07\n\x03OUT\x10\x00\x12\x07\n\x03\x45RR\x10\x01\"B\n\x07\x43ounter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x05\x64\x65lta\x18\x02 \x01(\x04H\x00\x12\x0f\n\x05total\x18\x03 \x01(\x04H\x00\x42\x07\n\x05value\"\x88\x01\n\x05Gauge\x12\x33\n\x07metrics\x18\x01 \x03(\x0b\x32\".loggregator.v2.Gauge.MetricsEntry\x1aJ\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.loggregator.v2.GaugeValue:\x02\x38\x01\")\n\nGaugeValue\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"2\n\x05Timer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x03\x12\x0c\n\x04stop\x18\x03 \x01(\x03\x62\x06proto3')
)



_LOG_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='loggregator.v2.Log.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OUT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=530,
  serialized_end=554,
)
_sym_db.RegisterEnumDescriptor(_LOG_TYPE)


_ENVELOPE_TAGSENTRY = _descriptor.Descriptor(
  name='TagsEntry',
  full_name='loggregator.v2.Envelope.TagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='loggregator.v2.Envelope.TagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='loggregator.v2.Envelope.TagsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=382,
)

_ENVELOPE = _descriptor.Descriptor(
  name='Envelope',
  full_name='loggregator.v2.Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='loggregator.v2.Envelope.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='loggregator.v2.Envelope.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='loggregator.v2.Envelope.instance_id', index=2,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='loggregator.v2.Envelope.tags', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log', full_name='loggregator.v2.Envelope.log', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counter', full_name='loggregator.v2.Envelope.counter', index=5,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gauge', full_name='loggregator.v2.Envelope.gauge', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timer', full_name='loggregator.v2.Envelope.timer', index=7,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ENVELOPE_TAGSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='loggregator.v2.Envelope.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=35,
  serialized_end=393,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='loggregator.v2.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='loggregator.v2.Value.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integer', full_name='loggregator.v2.Value.integer', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decimal', full_name='loggregator.v2.Value.decimal', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='loggregator.v2.Value.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=395,
  serialized_end=464,
)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='loggregator.v2.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='loggregator.v2.Log.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='loggregator.v2.Log.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOG_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=554,
)


_COUNTER = _descriptor.Descriptor(
  name='Counter',
  full_name='loggregator.v2.Counter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='loggregator.v2.Counter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta', full_name='loggregator.v2.Counter.delta', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total', full_name='loggregator.v2.Counter.total', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='loggregator.v2.Counter.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=556,
  serialized_end=622,
)


_GAUGE_METRICSENTRY = _descriptor.Descriptor(
  name='MetricsEntry',
  full_name='loggregator.v2.Gauge.MetricsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='loggregator.v2.Gauge.MetricsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='loggregator.v2.Gauge.MetricsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=687,
  serialized_end=761,
)

_GAUGE = _descriptor.Descriptor(
  name='Gauge',
  full_name='loggregator.v2.Gauge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='loggregator.v2.Gauge.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GAUGE_METRICSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=761,
)


_GAUGEVALUE = _descriptor.Descriptor(
  name='GaugeValue',
  full_name='loggregator.v2.GaugeValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit', full_name='loggregator.v2.GaugeValue.unit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='loggregator.v2.GaugeValue.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=763,
  serialized_end=804,
)


_TIMER = _descriptor.Descriptor(
  name='Timer',
  full_name='loggregator.v2.Timer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='loggregator.v2.Timer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='loggregator.v2.Timer.start', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop', full_name='loggregator.v2.Timer.stop', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=806,
  serialized_end=856,
)

_ENVELOPE_TAGSENTRY.fields_by_name['value'].message_type = _VALUE
_ENVELOPE_TAGSENTRY.containing_type = _ENVELOPE
_ENVELOPE.fields_by_name['tags'].message_type = _ENVELOPE_TAGSENTRY
_ENVELOPE.fields_by_name['log'].message_type = _LOG
_ENVELOPE.fields_by_name['counter'].message_type = _COUNTER
_ENVELOPE.fields_by_name['gauge'].message_type = _GAUGE
_ENVELOPE.fields_by_name['timer'].message_type = _TIMER
_ENVELOPE.oneofs_by_name['message'].fields.append(
  _ENVELOPE.fields_by_name['log'])
_ENVELOPE.fields_by_name['log'].containing_oneof = _ENVELOPE.oneofs_by_name['message']
_ENVELOPE.oneofs_by_name['message'].fields.append(
  _ENVELOPE.fields_by_name['counter'])
_ENVELOPE.fields_by_name['counter'].containing_oneof = _ENVELOPE.oneofs_by_name['message']
_ENVELOPE.oneofs_by_name['message'].fields.append(
  _ENVELOPE.fields_by_name['gauge'])
_ENVELOPE.fields_by_name['gauge'].containing_oneof = _ENVELOPE.oneofs_by_name['message']
_ENVELOPE.oneofs_by_name['message'].fields.append(
  _ENVELOPE.fields_by_name['timer'])
_ENVELOPE.fields_by_name['timer'].containing_oneof = _ENVELOPE.oneofs_by_name['message']
_VALUE.oneofs_by_name['data'].fields.append(
  _VALUE.fields_by_name['text'])
_VALUE.fields_by_name['text'].containing_oneof = _VALUE.oneofs_by_name['data']
_VALUE.oneofs_by_name['data'].fields.append(
  _VALUE.fields_by_name['integer'])
_VALUE.fields_by_name['integer'].containing_oneof = _VALUE.oneofs_by_name['data']
_VALUE.oneofs_by_name['data'].fields.append(
  _VALUE.fields_by_name['decimal'])
_VALUE.fields_by_name['decimal'].containing_oneof = _VALUE.oneofs_by_name['data']
_LOG.fields_by_name['type'].enum_type = _LOG_TYPE
_LOG_TYPE.containing_type = _LOG
_COUNTER.oneofs_by_name['value'].fields.append(
  _COUNTER.fields_by_name['delta'])
_COUNTER.fields_by_name['delta'].containing_oneof = _COUNTER.oneofs_by_name['value']
_COUNTER.oneofs_by_name['value'].fields.append(
  _COUNTER.fields_by_name['total'])
_COUNTER.fields_by_name['total'].containing_oneof = _COUNTER.oneofs_by_name['value']
_GAUGE_METRICSENTRY.fields_by_name['value'].message_type = _GAUGEVALUE
_GAUGE_METRICSENTRY.containing_type = _GAUGE
_GAUGE.fields_by_name['metrics'].message_type = _GAUGE_METRICSENTRY
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['Counter'] = _COUNTER
DESCRIPTOR.message_types_by_name['Gauge'] = _GAUGE
DESCRIPTOR.message_types_by_name['GaugeValue'] = _GAUGEVALUE
DESCRIPTOR.message_types_by_name['Timer'] = _TIMER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Envelope = _reflection.GeneratedProtocolMessageType('Envelope', (_message.Message,), dict(

  TagsEntry = _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), dict(
    DESCRIPTOR = _ENVELOPE_TAGSENTRY,
    __module__ = 'envelope_pb2'
    # @@protoc_insertion_point(class_scope:loggregator.v2.Envelope.TagsEntry)
    ))
  ,
  DESCRIPTOR = _ENVELOPE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.Envelope)
  ))
_sym_db.RegisterMessage(Envelope)
_sym_db.RegisterMessage(Envelope.TagsEntry)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.Value)
  ))
_sym_db.RegisterMessage(Value)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), dict(
  DESCRIPTOR = _LOG,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.Log)
  ))
_sym_db.RegisterMessage(Log)

Counter = _reflection.GeneratedProtocolMessageType('Counter', (_message.Message,), dict(
  DESCRIPTOR = _COUNTER,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.Counter)
  ))
_sym_db.RegisterMessage(Counter)

Gauge = _reflection.GeneratedProtocolMessageType('Gauge', (_message.Message,), dict(

  MetricsEntry = _reflection.GeneratedProtocolMessageType('MetricsEntry', (_message.Message,), dict(
    DESCRIPTOR = _GAUGE_METRICSENTRY,
    __module__ = 'envelope_pb2'
    # @@protoc_insertion_point(class_scope:loggregator.v2.Gauge.MetricsEntry)
    ))
  ,
  DESCRIPTOR = _GAUGE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.Gauge)
  ))
_sym_db.RegisterMessage(Gauge)
_sym_db.RegisterMessage(Gauge.MetricsEntry)

GaugeValue = _reflection.GeneratedProtocolMessageType('GaugeValue', (_message.Message,), dict(
  DESCRIPTOR = _GAUGEVALUE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.GaugeValue)
  ))
_sym_db.RegisterMessage(GaugeValue)

Timer = _reflection.GeneratedProtocolMessageType('Timer', (_message.Message,), dict(
  DESCRIPTOR = _TIMER,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.Timer)
  ))
_sym_db.RegisterMessage(Timer)


_ENVELOPE_TAGSENTRY.has_options = True
_ENVELOPE_TAGSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_GAUGE_METRICSENTRY.has_options = True
_GAUGE_METRICSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
