# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingress.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import envelope_pb2 as envelope__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ingress.proto',
  package='loggregator.v2',
  syntax='proto3',
  serialized_pb=_b('\n\ringress.proto\x12\x0eloggregator.v2\x1a\x0e\x65nvelope.proto\"\x11\n\x0fIngressResponse\"8\n\rEnvelopeBatch\x12\'\n\x05\x62\x61tch\x18\x01 \x03(\x0b\x32\x18.loggregator.v2.Envelope\"\x15\n\x13\x42\x61tchSenderResponse2\xa9\x01\n\x07Ingress\x12G\n\x06Sender\x12\x18.loggregator.v2.Envelope\x1a\x1f.loggregator.v2.IngressResponse\"\x00(\x01\x12U\n\x0b\x42\x61tchSender\x12\x1d.loggregator.v2.EnvelopeBatch\x1a#.loggregator.v2.BatchSenderResponse\"\x00(\x01\x62\x06proto3')
  ,
  dependencies=[envelope__pb2.DESCRIPTOR,])




_INGRESSRESPONSE = _descriptor.Descriptor(
  name='IngressResponse',
  full_name='loggregator.v2.IngressResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=66,
)


_ENVELOPEBATCH = _descriptor.Descriptor(
  name='EnvelopeBatch',
  full_name='loggregator.v2.EnvelopeBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch', full_name='loggregator.v2.EnvelopeBatch.batch', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=124,
)


_BATCHSENDERRESPONSE = _descriptor.Descriptor(
  name='BatchSenderResponse',
  full_name='loggregator.v2.BatchSenderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=147,
)

_ENVELOPEBATCH.fields_by_name['batch'].message_type = envelope__pb2._ENVELOPE
DESCRIPTOR.message_types_by_name['IngressResponse'] = _INGRESSRESPONSE
DESCRIPTOR.message_types_by_name['EnvelopeBatch'] = _ENVELOPEBATCH
DESCRIPTOR.message_types_by_name['BatchSenderResponse'] = _BATCHSENDERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IngressResponse = _reflection.GeneratedProtocolMessageType('IngressResponse', (_message.Message,), dict(
  DESCRIPTOR = _INGRESSRESPONSE,
  __module__ = 'ingress_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.IngressResponse)
  ))
_sym_db.RegisterMessage(IngressResponse)

EnvelopeBatch = _reflection.GeneratedProtocolMessageType('EnvelopeBatch', (_message.Message,), dict(
  DESCRIPTOR = _ENVELOPEBATCH,
  __module__ = 'ingress_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.EnvelopeBatch)
  ))
_sym_db.RegisterMessage(EnvelopeBatch)

BatchSenderResponse = _reflection.GeneratedProtocolMessageType('BatchSenderResponse', (_message.Message,), dict(
  DESCRIPTOR = _BATCHSENDERRESPONSE,
  __module__ = 'ingress_pb2'
  # @@protoc_insertion_point(class_scope:loggregator.v2.BatchSenderResponse)
  ))
_sym_db.RegisterMessage(BatchSenderResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IngressStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Sender = channel.stream_unary(
          '/loggregator.v2.Ingress/Sender',
          request_serializer=envelope__pb2.Envelope.SerializeToString,
          response_deserializer=IngressResponse.FromString,
          )
      self.BatchSender = channel.stream_unary(
          '/loggregator.v2.Ingress/BatchSender',
          request_serializer=EnvelopeBatch.SerializeToString,
          response_deserializer=BatchSenderResponse.FromString,
          )


  class IngressServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Sender(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def BatchSender(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IngressServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Sender': grpc.stream_unary_rpc_method_handler(
            servicer.Sender,
            request_deserializer=envelope__pb2.Envelope.FromString,
            response_serializer=IngressResponse.SerializeToString,
        ),
        'BatchSender': grpc.stream_unary_rpc_method_handler(
            servicer.BatchSender,
            request_deserializer=EnvelopeBatch.FromString,
            response_serializer=BatchSenderResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'loggregator.v2.Ingress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIngressServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Sender(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def BatchSender(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIngressStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Sender(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Sender.future = None
    def BatchSender(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    BatchSender.future = None


  def beta_create_Ingress_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('loggregator.v2.Ingress', 'BatchSender'): EnvelopeBatch.FromString,
      ('loggregator.v2.Ingress', 'Sender'): envelope__pb2.Envelope.FromString,
    }
    response_serializers = {
      ('loggregator.v2.Ingress', 'BatchSender'): BatchSenderResponse.SerializeToString,
      ('loggregator.v2.Ingress', 'Sender'): IngressResponse.SerializeToString,
    }
    method_implementations = {
      ('loggregator.v2.Ingress', 'BatchSender'): face_utilities.stream_unary_inline(servicer.BatchSender),
      ('loggregator.v2.Ingress', 'Sender'): face_utilities.stream_unary_inline(servicer.Sender),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Ingress_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('loggregator.v2.Ingress', 'BatchSender'): EnvelopeBatch.SerializeToString,
      ('loggregator.v2.Ingress', 'Sender'): envelope__pb2.Envelope.SerializeToString,
    }
    response_deserializers = {
      ('loggregator.v2.Ingress', 'BatchSender'): BatchSenderResponse.FromString,
      ('loggregator.v2.Ingress', 'Sender'): IngressResponse.FromString,
    }
    cardinalities = {
      'BatchSender': cardinality.Cardinality.STREAM_UNARY,
      'Sender': cardinality.Cardinality.STREAM_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'loggregator.v2.Ingress', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
